name: Caller for PR validation workflow
# CAMARA Project - Github Action for Pull Reqests
# This workflow calls the reusable workflow from the tooling repository
# initial version

on:
  # Pull Requests to main
  pull_request:
    branches: main
  # manual workflow triggering
  workflow_dispatch:
  
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  pr_validation:
    uses: camaraproject/tooling/.github/workflows/pr_validation.yml@test-pr-validate-updates
    secrets: inherit
# This workflow calls the reusable workflow from tooling repository
# If the tooling workflow is not v0, it must be set below again in the variable tooling-ref
# (due to GitHub Actions limitation - cannot auto-detect @ref from uses: statement)
    with:
      tooling-ref: test-pr-validate-updates
